# Generated by Django 4.0.6 on 2022-08-03 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('system_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestedroom',
            name='booking_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.bookingrequest'),
        ),
        migrations.AddField(
            model_name='requestedroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='paid',
            name='booking_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.bookingrequest'),
        ),
        migrations.AddField(
            model_name='paid',
            name='payment_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.paymentinformation'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.hotel'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='room',
            field=models.ManyToManyField(through='customer.RequestedRoom', to='hotel.room'),
        ),
        migrations.AlterUniqueTogether(
            name='requestedroom',
            unique_together={('booking_request', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='paid',
            unique_together={('booking_request', 'transaction_id')},
        ),
    ]
